const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');
const prisma = new PrismaClient();

async function main() {
  await prisma.beer.createMany({
    data: [
      {
        name: 'Queue de Charrue',
        brewery: 'Vanuxeem',
        origin: 'Ploegsteert, Belgique',
        country: 'BE',
        abv: 9.0,
        price33: 2.6,
        price75: 5.6,
        glassName: 'Calice à pied Queue de Charrue',
        glassPrice: 4.9,
        description: "Triple blonde de 9%, refermentée en bouteille, à la mousse compacte et à l'amertume prolongée et équilibrée.",
        bottleImageUrl: '/beers/queue-de-charrue-triple-bouteille-verre.png',
      },
      {
        name: 'Anosteke Blonde',
        brewery: 'Brasserie du Pays Flamand',
        origin: 'Merville, Nord',
        country: 'FR',
        abv: 8.0,
        price33: 2.8,
        price75: 6.0,
        glassName: 'Verre ballon sculpté Anosteke',
        glassPrice: 6.5,
        description: 'Blonde du Nord aux notes fleuries et fruitées.',
        bottleImageUrl: '/beers/anosteke-blonde-bouteille.jpg',
      },
      {
        name: 'Anosteke NEIPA',
        brewery: 'Brasserie du Pays Flamand',
        origin: 'Merville, Nord',
        country: 'FR',
        abv: 5.6,
        price33: 0,
        price75: 6.0,
        description: "Blonde trouble, arômes puissants de fruits tropicaux et d'agrumes. Vendue en 75cl uniquement.",
        bottleImageUrl: '/beers/anosteke-neipa-bouteille.jpg',
      },
      {
        name: 'Anosteke Saison',
        brewery: 'Brasserie du Pays Flamand',
        origin: 'Merville, Nord',
        country: 'FR',
        abv: 6.0,
        price33: 2.8,
        price75: 6.0,
        description: 'Robe jaune doré, arômes de céréales, pain et notes florales.',
        bottleImageUrl: '/beers/anosteke-saison-bouteille.jpg',
      },
      {
        name: 'Queue de Charrue IPA',
        brewery: 'Vanuxeem',
        origin: 'Ploegsteert, Belgique',
        country: 'BE',
        abv: 5.9,
        price33: 2.6,
        price75: 5.6,
        glassName: 'Calice à pied Queue de Charrue',
        glassPrice: 4.9,
        description: 'Blonde légèrement trouble, dry-hopée au Mosaic, notes exotiques et fruitées.',
        bottleImageUrl: '/beers/queue-de-charrue-ipa-bouteille-verre.png',
      },
      {
        name: 'Queue de Charrue Blonde',
        brewery: 'Vanuxeem',
        origin: 'Ploegsteert, Belgique',
        country: 'BE',
        abv: 6.6,
        price33: 2.6,
        price75: 5.6,
        glassName: 'Calice à pied Queue de Charrue',
        glassPrice: 4.9,
        description: 'Haute fermentation, arômes subtils de houblon, amertume équilibrée et parfum légèrement fruité.',
        bottleImageUrl: '/beers/queue-de-charrue-blonde-bouteille.png',
      },
      {
        name: 'Queue de Charrue Brune',
        brewery: 'Vanuxeem',
        origin: 'Ploegsteert, Belgique',
        country: 'BE',
        abv: 5.4,
        price33: 2.6,
        price75: 5.6,
        glassName: 'Calice à pied Queue de Charrue',
        glassPrice: 4.9,
        description: 'Véritable bière rouge flamande, 18 mois en fûts de chêne, goût aigre-doux et fruité.',
        bottleImageUrl: '/beers/queue-de-charrue-brune-bouteille-verre.png',
      },
      {
        name: 'Ypra Triple',
        brewery: 'Omer Vander Ghinste',
        origin: 'Bissegem, Belgique',
        country: 'BE',
        abv: 10.0,
        price33: 3.2,
        price75: 6.8,
        description: "Triple dorée à la mousse crémeuse, arômes houblonnés d'orange, mandarine et pamplemousse.",
        bottleImageUrl: '/beers/ypra-triple-bouteille-verre.png',
      },
      {
        name: '3 Monts IPA',
        brewery: 'Brasserie de Saint-Sylvestre',
        origin: 'Saint-Sylvestre-Cappel, Nord',
        country: 'FR',
        abv: 0,
        price33: 2.9,
        price75: 6.2,
        glassName: 'Verre 3 Monts',
        glassPrice: 5.0,
        description: "Recette houblonnée aux houblons Callista et Sabro, notes de fruits exotiques et d'agrumes.",
        bottleImageUrl: '/beers/3monts-ipa-bouteille.png',
        glassImageUrl: '/beers/3monts-ipa-verre.png',
      },
      {
        name: '3 Monts Blonde',
        brewery: 'Brasserie de Saint-Sylvestre',
        origin: 'Saint-Sylvestre-Cappel, Nord',
        country: 'FR',
        abv: 0,
        price33: 2.7,
        price75: 5.8,
        description: "L'iconique bière blonde or, limpide, notes de céréales et houblon herbacé, saveurs de malt et de fruit.",
        bottleImageUrl: '/beers/3monts-blonde-bouteille-verre.png',
      },
      {
        name: '3 Monts Ambrée',
        brewery: 'Brasserie de Saint-Sylvestre',
        origin: 'Saint-Sylvestre-Cappel, Nord',
        country: 'FR',
        abv: 0,
        price33: 2.9,
        price75: 6.2,
        glassName: 'Verre 3 Monts',
        glassPrice: 5.0,
        description: 'Couleur cuivrée, notes de caramel, miel et pain toasté, saveurs de malts torréfiés.',
        bottleImageUrl: '/beers/3monts-ambree-bouteille.png',
        glassImageUrl: '/beers/3monts-verre.png',
      },
      {
        name: '3 Monts Saison',
        brewery: 'Brasserie de Saint-Sylvestre',
        origin: 'Saint-Sylvestre-Cappel, Nord',
        country: 'FR',
        abv: 0,
        price33: 2.7,
        price75: 5.8,
        glassName: 'Verre 3 Monts',
        glassPrice: 5.0,
        description: "Blonde dorée et désaltérante, notes d'agrumes et de houblon frais.",
        bottleImageUrl: '/beers/3monts-saison-bouteille.png',
        glassImageUrl: '/beers/3monts-verre.png',
      },
      {
        name: '3 Monts Triple',
        brewery: 'Brasserie de Saint-Sylvestre',
        origin: 'Saint-Sylvestre-Cappel, Nord',
        country: 'FR',
        abv: 0,
        price33: 3.1,
        price75: 6.6,
        glassName: 'Verre 3 Monts',
        glassPrice: 5.0,
        description: 'Blonde orangée typée, notes de banane mûre, fruits à noyaux et pain, finale longue et épicée.',
        bottleImageUrl: '/beers/3monts-triple-bouteille.png',
        glassImageUrl: '/beers/3monts-verre.png',
      },
      {
        name: 'Paix Dieu',
        brewery: 'Brasserie du Bocq',
        origin: 'Abbaye de Bonlieu, Belgique',
        country: 'BE',
        abv: 10.0,
        price33: 3.2,
        price75: 6.8,
        glassName: 'Verre demi-lune Paix Dieu',
        glassPrice: 5.5,
        description: "Triple d'abbaye ronde et épicée.",
        bottleImageUrl: '/beers/paix-dieu-bouteille.png',
        glassImageUrl: '/beers/paix-dieu-verre.webp',
      },
      {
        name: 'Chouffe',
        brewery: "Brasserie d'Achouffe",
        origin: 'Achouffe, Belgique',
        country: 'BE',
        abv: 8.0,
        price33: 3.0,
        price75: 6.4,
        glassName: 'Verre ballon Chouffe',
        glassPrice: 7.2,
        description: 'Blonde emblématique des Ardennes belges.',
        bottleImageUrl: '/beers/chouffe-bouteille.png',
        glassImageUrl: '/beers/chouffe-verre.png',
      },
    ],
  });

  // Compte admin de démarrage — À CHANGER le mot de passe immédiatement après le premier déploiement
  const existingAdmin = await prisma.user.findUnique({ where: { email: 'admin@houbloncheztoi.fr' } });
  if (!existingAdmin) {
    const passwordHash = await bcrypt.hash('change-moi-immediatement', 10);
    await prisma.user.create({
      data: {
        name: 'Admin',
        email: 'admin@houbloncheztoi.fr',
        passwordHash,
        town: 'Bondues',
        isAdmin: true,
      },
    });
  }

  console.log('Seed terminé.');
}

main().finally(() => prisma.$disconnect());
